# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='host_groups',
            new_name='host_group',
        ),
    ]
