# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 07:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auto_20170223_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_tag', models.CharField(max_length=128, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('host_2_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.HostToUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
